# SPDX-FileCopyrightText: 2026 ModelCloud.ai
# SPDX-FileCopyrightText: 2026 qubitium@modelcloud.ai
# SPDX-License-Identifier: Apache-2.0
# Contact: qubitium@modelcloud.ai, x.com/qubitium

from __future__ import annotations

import importlib

from datasets import Dataset

import evalution
from evalution.engines.base import LoglikelihoodOutput

mmlu_module = importlib.import_module("evalution.suites.mmlu")


class FakeSession:
    def loglikelihood(self, requests, *, batch_size=None):
        assert batch_size == 11
        assert len(requests) == 8
        assert "The following are multiple choice questions (with answers) about abstract algebra." in requests[0].context
        assert "2 + 2 equals\nA. 1\nB. 2\nC. 3\nD. 4\nAnswer: D" in requests[0].context
        assert requests[0].context.endswith("The cyclic subgroup of Z_24 generated by 18 has order\nA. 4\nB. 8\nC. 12\nD. 6\nAnswer:")
        assert requests[0].continuation == " A"
        assert "The following are multiple choice questions (with answers) about machine learning." in requests[4].context
        return [
            LoglikelihoodOutput(logprob=-0.1, is_greedy=True, token_count=1),
            LoglikelihoodOutput(logprob=-0.4, is_greedy=False, token_count=1),
            LoglikelihoodOutput(logprob=-0.7, is_greedy=False, token_count=1),
            LoglikelihoodOutput(logprob=-0.9, is_greedy=False, token_count=1),
            LoglikelihoodOutput(logprob=-1.2, is_greedy=False, token_count=1),
            LoglikelihoodOutput(logprob=-0.2, is_greedy=True, token_count=1),
            LoglikelihoodOutput(logprob=-0.5, is_greedy=False, token_count=1),
            LoglikelihoodOutput(logprob=-0.8, is_greedy=False, token_count=1),
        ]


def test_mmlu_uses_subset_matched_fewshot_prompts(monkeypatch) -> None:
    validation = Dataset.from_list(
        [
            {
                "question": "The cyclic subgroup of Z_24 generated by 18 has order",
                "subject": "abstract_algebra",
                "choices": ["4", "8", "12", "6"],
                "answer": 0,
            },
            {
                "question": "Gradient descent is mainly used to",
                "subject": "machine_learning",
                "choices": ["sort labels", "optimize parameters", "render charts", "tokenize text"],
                "answer": 1,
            },
        ]
    )
    dev = Dataset.from_list(
        [
            {
                "question": "2 + 2 equals",
                "subject": "abstract_algebra",
                "choices": ["1", "2", "3", "4"],
                "answer": 3,
            },
            {
                "question": "A validation set is used to",
                "subject": "machine_learning",
                "choices": ["train forever", "tune hyperparameters", "wash data", "store gradients"],
                "answer": 1,
            },
        ]
    )

    def fake_load_dataset(path, name=None, *, split=None, **kwargs):
        del path, name, kwargs
        if split == "validation":
            return validation
        if split == "dev":
            return dev
        raise AssertionError(f"unexpected split: {split}")

    monkeypatch.setattr(mmlu_module, "load_dataset", fake_load_dataset)

    result = evalution.mmlu(subset="all", num_fewshot=1, max_rows=2, batch_size=11).evaluate(FakeSession())

    assert result.name == "mmlu"
    assert result.metrics == {
        "accuracy,loglikelihood": 1.0,
        "accuracy,loglikelihood_norm": 1.0,
    }
    assert result.metadata["dataset_path"] == "cais/mmlu"
    assert result.metadata["dataset_name"] == "all"
    assert result.metadata["subset"] == "all"
    assert result.metadata["subset_path"] == ["all"]
    assert result.metadata["subset_kind"] == "all"
    assert result.metadata["fewshot_split"] == "dev"
    assert result.metadata["num_fewshot"] == 1
    assert len(result.samples) == 2

    first = result.samples[0]
    assert first.target == "A"
    assert first.prediction == "A"
    assert first.metadata["subset"] == "stem.abstract_algebra"
    assert first.metadata["subset_path"] == ["stem", "abstract_algebra"]
    assert first.metadata["subset_kind"] == "leaf"
    assert first.metadata["subset_value"] == "abstract_algebra"
    assert first.metadata["choice_texts"] == ["4", "8", "12", "6"]

    second = result.samples[1]
    assert second.target == "B"
    assert second.prediction == "B"
    assert second.metadata["subset"] == "stem.machine_learning"


def test_mmlu_subset_node_filter_uses_distinct_result_name(monkeypatch) -> None:
    validation = Dataset.from_list(
        [
            {
                "question": "The cyclic subgroup of Z_24 generated by 18 has order",
                "subject": "abstract_algebra",
                "choices": ["4", "8", "12", "6"],
                "answer": 0,
            },
            {
                "question": "Gradient descent is mainly used to",
                "subject": "machine_learning",
                "choices": ["sort labels", "optimize parameters", "render charts", "tokenize text"],
                "answer": 1,
            },
            {
                "question": "A senate is usually part of",
                "subject": "high_school_government_and_politics",
                "choices": ["biology", "politics", "physics", "art"],
                "answer": 1,
            },
        ]
    )
    dev = Dataset.from_list(
        [
            {
                "question": "2 + 2 equals",
                "subject": "abstract_algebra",
                "choices": ["1", "2", "3", "4"],
                "answer": 3,
            },
            {
                "question": "A validation set is used to",
                "subject": "machine_learning",
                "choices": ["train forever", "tune hyperparameters", "wash data", "store gradients"],
                "answer": 1,
            },
            {
                "question": "A president is elected by",
                "subject": "high_school_government_and_politics",
                "choices": ["atoms", "voters", "enzymes", "planets"],
                "answer": 1,
            },
        ]
    )

    def fake_load_dataset(path, name=None, *, split=None, **kwargs):
        del path, name, kwargs
        if split == "validation":
            return validation
        if split == "dev":
            return dev
        raise AssertionError(f"unexpected split: {split}")

    class StemSession:
        def loglikelihood(self, requests, *, batch_size=None):
            assert batch_size == 8
            assert len(requests) == 8
            assert all(
                "high school government and politics" not in request.context
                for request in requests
            )
            return [
                LoglikelihoodOutput(logprob=-0.1, is_greedy=True, token_count=1),
                LoglikelihoodOutput(logprob=-0.4, is_greedy=False, token_count=1),
                LoglikelihoodOutput(logprob=-0.7, is_greedy=False, token_count=1),
                LoglikelihoodOutput(logprob=-0.9, is_greedy=False, token_count=1),
                LoglikelihoodOutput(logprob=-1.2, is_greedy=False, token_count=1),
                LoglikelihoodOutput(logprob=-0.2, is_greedy=True, token_count=1),
                LoglikelihoodOutput(logprob=-0.5, is_greedy=False, token_count=1),
                LoglikelihoodOutput(logprob=-0.8, is_greedy=False, token_count=1),
            ]

    monkeypatch.setattr(mmlu_module, "load_dataset", fake_load_dataset)

    result = evalution.mmlu(subset="stem", num_fewshot=1, max_rows=2, batch_size=8).evaluate(
        StemSession()
    )

    assert result.name == "mmlu_stem"
    assert result.metadata["dataset_name"] == "all"
    assert result.metadata["subset"] == "stem"
    assert result.metadata["subset_path"] == ["stem"]
    assert result.metadata["subset_kind"] == "node"
    assert len(result.samples) == 2
    assert {sample.metadata["subset"] for sample in result.samples} == {
        "stem.abstract_algebra",
        "stem.machine_learning",
    }


def test_mmlu_subset_leaf_filter_uses_canonical_path_name(monkeypatch) -> None:
    validation = Dataset.from_list(
        [
            {
                "question": "The cyclic subgroup of Z_24 generated by 18 has order",
                "subject": "abstract_algebra",
                "choices": ["4", "8", "12", "6"],
                "answer": 0,
            },
            {
                "question": "Gradient descent is mainly used to",
                "subject": "machine_learning",
                "choices": ["sort labels", "optimize parameters", "render charts", "tokenize text"],
                "answer": 1,
            },
        ]
    )
    dev = Dataset.from_list(
        [
            {
                "question": "2 + 2 equals",
                "subject": "abstract_algebra",
                "choices": ["1", "2", "3", "4"],
                "answer": 3,
            },
            {
                "question": "A validation set is used to",
                "subject": "machine_learning",
                "choices": ["train forever", "tune hyperparameters", "wash data", "store gradients"],
                "answer": 1,
            },
        ]
    )

    def fake_load_dataset(path, name=None, *, split=None, **kwargs):
        del path, name, kwargs
        if split == "validation":
            return validation
        if split == "dev":
            return dev
        raise AssertionError(f"unexpected split: {split}")

    class LeafSession:
        def loglikelihood(self, requests, *, batch_size=None):
            assert batch_size == 4
            assert len(requests) == 4
            assert all("machine learning" not in request.context for request in requests)
            return [
                LoglikelihoodOutput(logprob=-0.1, is_greedy=True, token_count=1),
                LoglikelihoodOutput(logprob=-0.4, is_greedy=False, token_count=1),
                LoglikelihoodOutput(logprob=-0.7, is_greedy=False, token_count=1),
                LoglikelihoodOutput(logprob=-0.9, is_greedy=False, token_count=1),
            ]

    monkeypatch.setattr(mmlu_module, "load_dataset", fake_load_dataset)

    result = evalution.mmlu(
        subset="stem.abstract_algebra",
        num_fewshot=1,
        max_rows=1,
        batch_size=4,
    ).evaluate(LeafSession())

    assert result.name == "mmlu_stem_abstract_algebra"
    assert result.metadata["dataset_name"] == "abstract_algebra"
    assert result.metadata["subset"] == "stem.abstract_algebra"
    assert result.metadata["subset_path"] == ["stem", "abstract_algebra"]
    assert result.metadata["subset_kind"] == "leaf"
    assert len(result.samples) == 1
    assert result.samples[0].metadata["subset"] == "stem.abstract_algebra"


def test_mmlu_format_helpers_render_subject_titles_and_examples() -> None:
    assert mmlu_module._format_subject_title("high_school_world_history") == "high school world history"
    assert mmlu_module._format_mmlu_question(
        {"question": "Example?", "choices": ["A1", "B1", "C1", "D1"], "answer": 2},
        include_answer=True,
    ) == "Example?\nA. A1\nB. B1\nC. C1\nD. D1\nAnswer: C"
