# SPDX-FileCopyrightText: 2026 ModelCloud.ai
# SPDX-FileCopyrightText: 2026 qubitium@modelcloud.ai
# SPDX-License-Identifier: Apache-2.0
# Contact: qubitium@modelcloud.ai, x.com/qubitium

from __future__ import annotations

import importlib

from datasets import Dataset

import evalution
from evalution.engines.base import LoglikelihoodOutput

mmlu_module = importlib.import_module("evalution.suites.mmlu")


class FakeSession:
    # Return deterministic per-choice scores so the suite can be tested without a real model.
    def loglikelihood(self, requests, *, batch_size=None):
        assert batch_size == 11
        assert len(requests) == 8
        assert "The following are multiple choice questions (with answers) about abstract algebra." in requests[0].context
        assert "2 + 2 equals\nA. 1\nB. 2\nC. 3\nD. 4\nAnswer: D" in requests[0].context
        assert requests[0].context.endswith("The cyclic subgroup of Z_24 generated by 18 has order\nA. 4\nB. 8\nC. 12\nD. 6\nAnswer:")
        assert requests[0].continuation == " A"
        assert "The following are multiple choice questions (with answers) about machine learning." in requests[4].context
        return [
            LoglikelihoodOutput(logprob=-0.1, is_greedy=True, token_count=1),
            LoglikelihoodOutput(logprob=-0.4, is_greedy=False, token_count=1),
            LoglikelihoodOutput(logprob=-0.7, is_greedy=False, token_count=1),
            LoglikelihoodOutput(logprob=-0.9, is_greedy=False, token_count=1),
            LoglikelihoodOutput(logprob=-1.2, is_greedy=False, token_count=1),
            LoglikelihoodOutput(logprob=-0.2, is_greedy=True, token_count=1),
            LoglikelihoodOutput(logprob=-0.5, is_greedy=False, token_count=1),
            LoglikelihoodOutput(logprob=-0.8, is_greedy=False, token_count=1),
        ]


def test_mmlu_uses_subject_matched_fewshot_prompts(monkeypatch) -> None:
    validation = Dataset.from_list(
        [
            {
                "question": "The cyclic subgroup of Z_24 generated by 18 has order",
                "subject": "abstract_algebra",
                "choices": ["4", "8", "12", "6"],
                "answer": 0,
            },
            {
                "question": "Gradient descent is mainly used to",
                "subject": "machine_learning",
                "choices": ["sort labels", "optimize parameters", "render charts", "tokenize text"],
                "answer": 1,
            },
        ]
    )
    dev = Dataset.from_list(
        [
            {
                "question": "2 + 2 equals",
                "subject": "abstract_algebra",
                "choices": ["1", "2", "3", "4"],
                "answer": 3,
            },
            {
                "question": "A validation set is used to",
                "subject": "machine_learning",
                "choices": ["train forever", "tune hyperparameters", "wash data", "store gradients"],
                "answer": 1,
            },
        ]
    )

    def fake_load_dataset(path, name=None, *, split=None, **kwargs):
        del path, name, kwargs
        if split == "validation":
            return validation
        if split == "dev":
            return dev
        raise AssertionError(f"unexpected split: {split}")

    monkeypatch.setattr(mmlu_module, "load_dataset", fake_load_dataset)

    result = evalution.mmlu(subject="all", num_fewshot=1, max_rows=2, batch_size=11).evaluate(FakeSession())

    assert result.name == "mmlu"
    assert result.metrics == {
        "accuracy,loglikelihood": 1.0,
        "accuracy,loglikelihood_norm": 1.0,
    }
    assert result.metadata["dataset_path"] == "cais/mmlu"
    assert result.metadata["dataset_name"] == "all"
    assert result.metadata["fewshot_split"] == "dev"
    assert result.metadata["num_fewshot"] == 1
    assert len(result.samples) == 2

    first = result.samples[0]
    assert first.target == "A"
    assert first.prediction == "A"
    assert first.metadata["subject"] == "abstract_algebra"
    assert first.metadata["choice_texts"] == ["4", "8", "12", "6"]

    second = result.samples[1]
    assert second.target == "B"
    assert second.prediction == "B"
    assert second.metadata["subject"] == "machine_learning"


def test_mmlu_format_helpers_render_subject_titles_and_examples() -> None:
    assert mmlu_module._format_subject_title("high_school_world_history") == "high school world history"
    assert mmlu_module._format_mmlu_question(
        {"question": "Example?", "choices": ["A1", "B1", "C1", "D1"], "answer": 2},
        include_answer=True,
    ) == "Example?\nA. A1\nB. B1\nC. C1\nD. D1\nAnswer: C"
