# SPDX-FileCopyrightText: 2026 ModelCloud.ai
# SPDX-FileCopyrightText: 2026 qubitium@modelcloud.ai
# SPDX-License-Identifier: Apache-2.0
# Contact: qubitium@modelcloud.ai, x.com/qubitium
# GPU=-1
from __future__ import annotations

import importlib
from types import SimpleNamespace

from datasets import Dataset

import evalution
from evalution.engines.base import LoglikelihoodOutput

# Keep shared test fixtures and expectations explicit at module scope.
mmlu_module = importlib.import_module("evalution.benchmarks.mmlu")


class FakeSession:
    """Provide the fake session helper used by the surrounding tests."""
    def loglikelihood(self, requests, *, batch_size=None):
        """Implement loglikelihood for fake session."""
        assert batch_size == 11
        assert len(requests) == 8
        assert "The following are multiple choice questions (with answers) about abstract algebra." in requests[0].context
        assert "2 + 2 equals\nA. 1\nB. 2\nC. 3\nD. 4\nAnswer: D" in requests[0].context
        assert requests[0].context.endswith("The cyclic subgroup of Z_24 generated by 18 has order\nA. 4\nB. 8\nC. 12\nD. 6\nAnswer:")
        assert requests[0].continuation == " A"
        assert "The following are multiple choice questions (with answers) about machine learning." in requests[4].context
        return [
            LoglikelihoodOutput(logprob=-0.1, is_greedy=True, token_count=1),
            LoglikelihoodOutput(logprob=-0.4, is_greedy=False, token_count=1),
            LoglikelihoodOutput(logprob=-0.7, is_greedy=False, token_count=1),
            LoglikelihoodOutput(logprob=-0.9, is_greedy=False, token_count=1),
            LoglikelihoodOutput(logprob=-1.2, is_greedy=False, token_count=1),
            LoglikelihoodOutput(logprob=-0.2, is_greedy=True, token_count=1),
            LoglikelihoodOutput(logprob=-0.5, is_greedy=False, token_count=1),
            LoglikelihoodOutput(logprob=-0.8, is_greedy=False, token_count=1),
        ]


def test_mmlu_uses_subset_matched_fewshot_prompts(monkeypatch) -> None:
    """Verify MMLU uses subset matched fewshot prompts."""
    test = Dataset.from_list(
        [
            {
                "question": "The cyclic subgroup of Z_24 generated by 18 has order",
                "subject": "abstract_algebra",
                "choices": ["4", "8", "12", "6"],
                "answer": 0,
            },
            {
                "question": "Gradient descent is mainly used to",
                "subject": "machine_learning",
                "choices": ["sort labels", "optimize parameters", "render charts", "tokenize text"],
                "answer": 1,
            },
        ]
    )
    dev = Dataset.from_list(
        [
            {
                "question": "2 + 2 equals",
                "subject": "abstract_algebra",
                "choices": ["1", "2", "3", "4"],
                "answer": 3,
            },
            {
                "question": "A validation set is used to",
                "subject": "machine_learning",
                "choices": ["train forever", "tune hyperparameters", "wash data", "store gradients"],
                "answer": 1,
            },
        ]
    )

    def fake_load_dataset(path, name=None, *, split=None, **kwargs):
        """Support the surrounding tests with fake load dataset."""
        del path, name, kwargs
        if split == "test":
            return test
        if split == "dev":
            return dev
        raise AssertionError(f"unexpected split: {split}")

    monkeypatch.setattr(mmlu_module, "load_dataset", fake_load_dataset)

    result = evalution.benchmarks.mmlu(subsets="all", num_fewshot=1, max_rows=2, batch_size=11).evaluate(FakeSession())

    assert result.name == "mmlu"
    assert result.metrics == {
        "acc,ll": 1.0,
        "acc,ll_avg": 1.0,
    }
    assert result.metadata["dataset_path"] == "cais/mmlu"
    assert result.metadata["dataset_name"] == "all"
    assert result.metadata["subsets"] == ["all"]
    assert result.metadata["subset_paths"] == [["all"]]
    assert result.metadata["subset_kinds"] == ["all"]
    assert result.metadata["selection_mode"] == "single"
    assert result.metadata["fewshot_split"] == "dev"
    assert result.metadata["num_fewshot"] == 1
    assert len(result.samples) == 2

    first = result.samples[0]
    assert first.target == "A"
    assert first.prediction == "A"
    assert first.metadata["subset"] == "stem.abstract_algebra"
    assert first.metadata["subset_path"] == ["stem", "abstract_algebra"]
    assert first.metadata["subset_kind"] == "leaf"
    assert first.metadata["subset_value"] == "abstract_algebra"
    assert first.metadata["choice_texts"] == ["4", "8", "12", "6"]

    second = result.samples[1]
    assert second.target == "B"
    assert second.prediction == "B"
    assert second.metadata["subset"] == "stem.machine_learning"


def test_mmlu_split_override_uses_requested_split(monkeypatch) -> None:
    """Verify MMLU split override uses requested split."""
    validation = Dataset.from_list(
        [
            {
                "question": "The cyclic subgroup of Z_24 generated by 18 has order",
                "subject": "abstract_algebra",
                "choices": ["4", "8", "12", "6"],
                "answer": 0,
            },
        ]
    )
    dev = Dataset.from_list(
        [
            {
                "question": "2 + 2 equals",
                "subject": "abstract_algebra",
                "choices": ["1", "2", "3", "4"],
                "answer": 3,
            },
        ]
    )

    def fake_load_dataset(path, name=None, *, split=None, **kwargs):
        """Support the surrounding tests with fake load dataset."""
        del path, name, kwargs
        if split == "validation":
            return validation
        if split == "dev":
            return dev
        raise AssertionError(f"unexpected split: {split}")

    class ValidationOnlySession:
        """Define the validation only session helper used by the surrounding tests."""
        def loglikelihood(self, requests, *, batch_size=None):
            """Implement loglikelihood for validation only session."""
            assert batch_size == 4
            assert len(requests) == 4
            assert requests[0].continuation == " A"
            return [
                LoglikelihoodOutput(logprob=-0.1, is_greedy=True, token_count=1),
                LoglikelihoodOutput(logprob=-0.4, is_greedy=False, token_count=1),
                LoglikelihoodOutput(logprob=-0.7, is_greedy=False, token_count=1),
                LoglikelihoodOutput(logprob=-0.9, is_greedy=False, token_count=1),
            ]

    monkeypatch.setattr(mmlu_module, "load_dataset", fake_load_dataset)

    result = evalution.benchmarks.mmlu(
        split="validation",
        num_fewshot=1,
        max_rows=1,
        batch_size=4,
    ).evaluate(ValidationOnlySession())

    assert result.metadata["split"] == "validation"
    assert len(result.samples) == 1


def test_mmlu_marks_dev_load_as_fewshot_dataset(monkeypatch) -> None:
    """Verify MMLU marks dev load as fewshot dataset."""
    test = Dataset.from_list(
        [
            {
                "question": "The cyclic subgroup of Z_24 generated by 18 has order",
                "subject": "abstract_algebra",
                "choices": ["4", "8", "12", "6"],
                "answer": 0,
            },
        ]
    )
    dev = Dataset.from_list(
        [
            {
                "question": "2 + 2 equals",
                "subject": "abstract_algebra",
                "choices": ["1", "2", "3", "4"],
                "answer": 3,
            },
        ]
    )
    load_calls: list[tuple[str, str | None]] = []

    def fake_load_suite_dataset(
        loader,
        *,
        task_name,
        dataset_path,
        dataset_name,
        split,
        cache_dir,
        stream,
        purpose=None,
    ):
        """Support the surrounding tests with fake load suite dataset."""
        del loader, task_name, dataset_path, dataset_name, cache_dir, stream
        load_calls.append((split, purpose))
        if split == "test":
            return test, 0.0
        if split == "dev":
            return dev, 0.0
        raise AssertionError(f"unexpected split: {split}")

    class PurposeSession:
        """Define the purpose session helper used by the surrounding tests."""
        def loglikelihood(self, requests, *, batch_size=None):
            """Implement loglikelihood for purpose session."""
            assert batch_size == 4
            assert len(requests) == 4
            return [
                LoglikelihoodOutput(logprob=-0.1, is_greedy=True, token_count=1),
                LoglikelihoodOutput(logprob=-0.4, is_greedy=False, token_count=1),
                LoglikelihoodOutput(logprob=-0.7, is_greedy=False, token_count=1),
                LoglikelihoodOutput(logprob=-0.9, is_greedy=False, token_count=1),
            ]

    monkeypatch.setattr(mmlu_module, "load_suite_dataset", fake_load_suite_dataset)

    result = evalution.benchmarks.mmlu(
        subsets="stem",
        num_fewshot=1,
        max_rows=1,
        batch_size=4,
    ).evaluate(PurposeSession())

    assert result.name == "mmlu_stem"
    assert load_calls == [("test", None), ("dev", "few-shot")]


def test_mmlu_streams_requests_into_loglikelihood_continuous(monkeypatch) -> None:
    """Verify MMLU streams requests into loglikelihood continuous."""
    test_doc = {
        "question": "The cyclic subgroup of Z_24 generated by 18 has order",
        "subject": "abstract_algebra",
        "choices": ["4", "8", "12", "6"],
        "answer": 0,
    }
    dev_doc = {
        "question": "2 + 2 equals",
        "subject": "abstract_algebra",
        "choices": ["1", "2", "3", "4"],
        "answer": 3,
    }

    class FailAfterFirstRowStream:
        """Define the fail after first row stream helper used by the surrounding tests."""
        def __init__(self, row, *, split: str) -> None:
            """Initialize this object."""
            self.row = dict(row)
            self.info = SimpleNamespace(
                splits={split: SimpleNamespace(num_examples=10)},
            )

        def __iter__(self):
            """Iterate over the items exposed by this object."""
            yield dict(self.row)
            raise AssertionError("stream consumed beyond max_rows")

    load_calls: list[tuple[str, str | None, str | None]] = []

    def fake_load_suite_dataset(
        loader,
        *,
        task_name,
        dataset_path,
        dataset_name,
        split,
        cache_dir,
        stream,
        purpose=None,
    ):
        """Support the surrounding tests with fake load suite dataset."""
        del loader, task_name, dataset_path, cache_dir, stream
        load_calls.append((split, dataset_name, purpose))
        if split == "test":
            return FailAfterFirstRowStream(test_doc, split=split), 0.0
        if split == "dev":
            return Dataset.from_list([dict(dev_doc)]), 0.0
        raise AssertionError(f"unexpected split: {split}")

    class ContinuousOnlySession:
        """Define the continuous only session helper used by the surrounding tests."""
        def loglikelihood(self, requests, *, batch_size=None):
            """Implement loglikelihood for continuous only session."""
            raise AssertionError("mmlu should use loglikelihood_continuous when available")

        def loglikelihood_continuous(self, requests, *, batch_size=None):
            """Implement loglikelihood continuous for continuous only session."""
            assert batch_size == 4
            for (sample_index, choice_index), request in requests:
                assert sample_index == 0
                assert "2 + 2 equals" in request.context
                yield (sample_index, choice_index), [
                    LoglikelihoodOutput(logprob=-0.1, is_greedy=True, token_count=1),
                    LoglikelihoodOutput(logprob=-0.4, is_greedy=False, token_count=1),
                    LoglikelihoodOutput(logprob=-0.7, is_greedy=False, token_count=1),
                    LoglikelihoodOutput(logprob=-0.9, is_greedy=False, token_count=1),
                ][choice_index]

    monkeypatch.setattr(mmlu_module, "load_suite_dataset", fake_load_suite_dataset)

    result = evalution.benchmarks.mmlu(
        subsets="all",
        num_fewshot=1,
        max_rows=1,
        batch_size=4,
        stream=True,
    ).evaluate(ContinuousOnlySession())

    assert result.name == "mmlu"
    assert result.metrics == {
        "acc,ll": 1.0,
        "acc,ll_avg": 1.0,
    }
    assert len(result.samples) == 1
    assert load_calls == [
        ("test", "all", None),
        ("dev", "all", "few-shot"),
    ]


def test_mmlu_subset_node_filter_uses_distinct_result_name(monkeypatch) -> None:
    """Verify MMLU subset node filter uses distinct result name."""
    test = Dataset.from_list(
        [
            {
                "question": "The cyclic subgroup of Z_24 generated by 18 has order",
                "subject": "abstract_algebra",
                "choices": ["4", "8", "12", "6"],
                "answer": 0,
            },
            {
                "question": "Gradient descent is mainly used to",
                "subject": "machine_learning",
                "choices": ["sort labels", "optimize parameters", "render charts", "tokenize text"],
                "answer": 1,
            },
            {
                "question": "A senate is usually part of",
                "subject": "high_school_government_and_politics",
                "choices": ["biology", "politics", "physics", "art"],
                "answer": 1,
            },
        ]
    )
    dev = Dataset.from_list(
        [
            {
                "question": "2 + 2 equals",
                "subject": "abstract_algebra",
                "choices": ["1", "2", "3", "4"],
                "answer": 3,
            },
            {
                "question": "A validation set is used to",
                "subject": "machine_learning",
                "choices": ["train forever", "tune hyperparameters", "wash data", "store gradients"],
                "answer": 1,
            },
            {
                "question": "A president is elected by",
                "subject": "high_school_government_and_politics",
                "choices": ["atoms", "voters", "enzymes", "planets"],
                "answer": 1,
            },
        ]
    )

    def fake_load_dataset(path, name=None, *, split=None, **kwargs):
        """Support the surrounding tests with fake load dataset."""
        del path, name, kwargs
        if split == "test":
            return test
        if split == "dev":
            return dev
        raise AssertionError(f"unexpected split: {split}")

    class StemSession:
        """Define the stem session helper used by the surrounding tests."""
        def loglikelihood(self, requests, *, batch_size=None):
            """Implement loglikelihood for stem session."""
            assert batch_size == 8
            assert len(requests) == 8
            assert all(
                "high school government and politics" not in request.context
                for request in requests
            )
            return [
                LoglikelihoodOutput(logprob=-0.1, is_greedy=True, token_count=1),
                LoglikelihoodOutput(logprob=-0.4, is_greedy=False, token_count=1),
                LoglikelihoodOutput(logprob=-0.7, is_greedy=False, token_count=1),
                LoglikelihoodOutput(logprob=-0.9, is_greedy=False, token_count=1),
                LoglikelihoodOutput(logprob=-1.2, is_greedy=False, token_count=1),
                LoglikelihoodOutput(logprob=-0.2, is_greedy=True, token_count=1),
                LoglikelihoodOutput(logprob=-0.5, is_greedy=False, token_count=1),
                LoglikelihoodOutput(logprob=-0.8, is_greedy=False, token_count=1),
            ]

    monkeypatch.setattr(mmlu_module, "load_dataset", fake_load_dataset)

    result = evalution.benchmarks.mmlu(subsets="stem", num_fewshot=1, max_rows=2, batch_size=8).evaluate(
        StemSession()
    )

    assert result.name == "mmlu_stem"
    assert result.metadata["dataset_name"] == "all"
    assert result.metadata["subsets"] == ["stem"]
    assert result.metadata["subset_paths"] == [["stem"]]
    assert result.metadata["subset_kinds"] == ["node"]
    assert result.metadata["selection_mode"] == "single"
    assert len(result.samples) == 2
    assert {sample.metadata["subset"] for sample in result.samples} == {
        "stem.abstract_algebra",
        "stem.machine_learning",
    }


def test_mmlu_subset_leaf_filter_uses_canonical_path_name(monkeypatch) -> None:
    """Verify MMLU subset leaf filter uses canonical path name."""
    test = Dataset.from_list(
        [
            {
                "question": "The cyclic subgroup of Z_24 generated by 18 has order",
                "subject": "abstract_algebra",
                "choices": ["4", "8", "12", "6"],
                "answer": 0,
            },
            {
                "question": "Gradient descent is mainly used to",
                "subject": "machine_learning",
                "choices": ["sort labels", "optimize parameters", "render charts", "tokenize text"],
                "answer": 1,
            },
        ]
    )
    dev = Dataset.from_list(
        [
            {
                "question": "2 + 2 equals",
                "subject": "abstract_algebra",
                "choices": ["1", "2", "3", "4"],
                "answer": 3,
            },
            {
                "question": "A validation set is used to",
                "subject": "machine_learning",
                "choices": ["train forever", "tune hyperparameters", "wash data", "store gradients"],
                "answer": 1,
            },
        ]
    )

    def fake_load_dataset(path, name=None, *, split=None, **kwargs):
        """Support the surrounding tests with fake load dataset."""
        del path, name, kwargs
        if split == "test":
            return test
        if split == "dev":
            return dev
        raise AssertionError(f"unexpected split: {split}")

    class LeafSession:
        """Define the leaf session helper used by the surrounding tests."""
        def loglikelihood(self, requests, *, batch_size=None):
            """Implement loglikelihood for leaf session."""
            assert batch_size == 4
            assert len(requests) == 4
            assert all("machine learning" not in request.context for request in requests)
            return [
                LoglikelihoodOutput(logprob=-0.1, is_greedy=True, token_count=1),
                LoglikelihoodOutput(logprob=-0.4, is_greedy=False, token_count=1),
                LoglikelihoodOutput(logprob=-0.7, is_greedy=False, token_count=1),
                LoglikelihoodOutput(logprob=-0.9, is_greedy=False, token_count=1),
            ]

    monkeypatch.setattr(mmlu_module, "load_dataset", fake_load_dataset)

    result = evalution.benchmarks.mmlu(
        subsets="stem.abstract_algebra",
        num_fewshot=1,
        max_rows=1,
        batch_size=4,
    ).evaluate(LeafSession())

    assert result.name == "mmlu_stem_abstract_algebra"
    assert result.metadata["dataset_name"] == "abstract_algebra"
    assert result.metadata["subsets"] == ["stem.abstract_algebra"]
    assert result.metadata["subset_paths"] == [["stem", "abstract_algebra"]]
    assert result.metadata["subset_kinds"] == ["leaf"]
    assert result.metadata["selection_mode"] == "single"
    assert len(result.samples) == 1
    assert result.samples[0].metadata["subset"] == "stem.abstract_algebra"


def test_mmlu_subsets_list_combines_multiple_paths(monkeypatch) -> None:
    """Verify MMLU subsets list combines multiple paths."""
    test = Dataset.from_list(
        [
            {
                "question": "The cyclic subgroup of Z_24 generated by 18 has order",
                "subject": "abstract_algebra",
                "choices": ["4", "8", "12", "6"],
                "answer": 0,
            },
            {
                "question": "A central topic in philosophy is",
                "subject": "philosophy",
                "choices": ["metaphysics", "enzymes", "gravity", "photosynthesis"],
                "answer": 0,
            },
            {
                "question": "Gradient descent is mainly used to",
                "subject": "machine_learning",
                "choices": ["sort labels", "optimize parameters", "render charts", "tokenize text"],
                "answer": 1,
            },
        ]
    )
    dev = Dataset.from_list(
        [
            {
                "question": "2 + 2 equals",
                "subject": "abstract_algebra",
                "choices": ["1", "2", "3", "4"],
                "answer": 3,
            },
            {
                "question": "A classical branch asks what is real",
                "subject": "philosophy",
                "choices": ["metaphysics", "chemistry", "geology", "astronomy"],
                "answer": 0,
            },
            {
                "question": "A validation set is used to",
                "subject": "machine_learning",
                "choices": ["train forever", "tune hyperparameters", "wash data", "store gradients"],
                "answer": 1,
            },
        ]
    )

    def fake_load_dataset(path, name=None, *, split=None, **kwargs):
        """Support the surrounding tests with fake load dataset."""
        del path, name, kwargs
        if split == "test":
            return test
        if split == "dev":
            return dev
        raise AssertionError(f"unexpected split: {split}")

    class MultiSession:
        """Define the multi session helper used by the surrounding tests."""
        def loglikelihood(self, requests, *, batch_size=None):
            """Implement loglikelihood for multi session."""
            assert batch_size == 8
            assert len(requests) == 8
            contexts = [request.context for request in requests[::4]]
            assert any("about abstract algebra." in context for context in contexts)
            assert any("about philosophy." in context for context in contexts)
            assert all("machine learning" not in context for context in contexts)
            return [
                LoglikelihoodOutput(logprob=-0.1, is_greedy=True, token_count=1),
                LoglikelihoodOutput(logprob=-0.4, is_greedy=False, token_count=1),
                LoglikelihoodOutput(logprob=-0.7, is_greedy=False, token_count=1),
                LoglikelihoodOutput(logprob=-0.9, is_greedy=False, token_count=1),
                LoglikelihoodOutput(logprob=-0.1, is_greedy=True, token_count=1),
                LoglikelihoodOutput(logprob=-0.4, is_greedy=False, token_count=1),
                LoglikelihoodOutput(logprob=-0.7, is_greedy=False, token_count=1),
                LoglikelihoodOutput(logprob=-0.9, is_greedy=False, token_count=1),
            ]

    monkeypatch.setattr(mmlu_module, "load_dataset", fake_load_dataset)

    result = evalution.benchmarks.mmlu(
        subsets=["stem.abstract_algebra", "humanities.philosophy"],
        num_fewshot=1,
        max_rows=2,
        batch_size=8,
    ).evaluate(MultiSession())

    assert result.name == "mmlu_stem_abstract_algebra__humanities_philosophy"
    assert result.metadata["dataset_name"] == "all"
    assert result.metadata["subsets"] == ["stem.abstract_algebra", "humanities.philosophy"]
    assert result.metadata["subset_paths"] == [
        ["stem", "abstract_algebra"],
        ["humanities", "philosophy"],
    ]
    assert result.metadata["subset_kinds"] == ["leaf", "leaf"]
    assert result.metadata["selection_mode"] == "multiple"
    assert {sample.metadata["subset"] for sample in result.samples} == {
        "stem.abstract_algebra",
        "humanities.philosophy",
    }


def test_mmlu_format_helpers_render_subject_titles_and_examples() -> None:
    """Verify MMLU format helpers render subject titles and examples."""
    assert mmlu_module._format_subject_title("high_school_world_history") == "high school world history"
    assert mmlu_module._format_mmlu_question(
        {"question": "Example?", "choices": ["A1", "B1", "C1", "D1"], "answer": 2},
        include_answer=True,
    ) == "Example?\nA. A1\nB. B1\nC. C1\nD. D1\nAnswer: C"
