# SPDX-FileCopyrightText: 2026 ModelCloud.ai
# SPDX-FileCopyrightText: 2026 qubitium@modelcloud.ai
# SPDX-License-Identifier: Apache-2.0
# Contact: qubitium@modelcloud.ai, x.com/qubitium

from __future__ import annotations

import pytest

from tests.models_support import LLAMA3_2_TRANSFORMERS_TEST_MARKS, run_suite_spec

pytestmark = LLAMA3_2_TRANSFORMERS_TEST_MARKS

SINGLE_SUITE_SPECS = (
    "anli_r1",
    "anli_r2",
    "anli_r3",
    "arc_challenge_label_perm_0_25",
    "arc_challenge",
    "arc_easy",
    "asdiv_cot_llama",
    "asdiv",
    "babi",
    "boolq",
    "c4",
    "cb",
    "click_cul_economy",
    "click_cul_geography",
    "click_cul_history",
    "click_cul_kpop",
    "click_cul_law",
    "click_cul",
    "click_cul_politics",
    "click_cul_society",
    "click_cul_tradition",
    "click_lang_function",
    "click_lang_grammar",
    "click_lang",
    "click_lang_text",
    "click",
    "cnn_dailymail",
    "cola",
    "commonsense_qa",
    "copa",
    "coqa",
    "darijahellaswag",
    "drop",
    "egyhellaswag",
    "ethics_cm",
    "ethics_deontology",
    "ethics_justice",
    "ethics_utilitarianism",
    "ethics_virtue",
    "eus_proficiency",
    "eus_reading",
    "eus_trivia",
    "fda",
    "fld",
    "french_bench_arc_challenge",
    "graphwalks_128k",
    "gsm8k",
    "gsm8k_platinum",
    "gsm_plus",
    "gsm_plus_mini",
    "haerae_general_knowledge",
    "haerae_history",
    "haerae",
    "haerae_loan_word",
    "haerae_rare_word",
    "haerae_standard_nomenclature",
    "headqa_en",
    "headqa_es",
    "hellaswag_label_perm_0_25",
    "hellaswag",
    "histoires_morales",
    "humaneval",
    "icelandic_winogrande",
    "ifeval",
    "kormedmcqa_dentist",
    "kormedmcqa_doctor",
    "kormedmcqa",
    "kormedmcqa_nurse",
    "kormedmcqa_pharm",
    "lambada_openai_cloze",
    "lambada_openai",
    "lambada_openai_mt_de",
    "lambada_openai_mt_en",
    "lambada_openai_mt_es",
    "lambada_openai_mt_fr",
    "lambada_openai_mt_it",
    "lambada_openai_mt_stablelm_de",
    "lambada_openai_mt_stablelm_en",
    "lambada_openai_mt_stablelm_es",
    "lambada_openai_mt_stablelm_fr",
    "lambada_openai_mt_stablelm_it",
    "lambada_openai_mt_stablelm_nl",
    "lambada_openai_mt_stablelm_pt",
    "lambada_standard_cloze",
    "lambada_standard",
    "logiqa",
    "mastermind_24_easy",
    "mastermind_24_hard",
    "mastermind_35_easy",
    "mastermind_35_hard",
    "mastermind_46_easy",
    "mastermind_46_hard",
    "mathqa",
    "mbpp",
    "mc_taco",
    "medmcqa",
    "medqa_4options",
    "mnli",
    "moral_stories",
    "mrpc",
    "nq_open",
    "openbookqa_label_perm_0_25",
    "openbookqa",
    "pile_10k",
    "piqa",
    "polemo2_in",
    "polemo2_out",
    "prost",
    "pubmedqa",
    "qnli",
    "qqp",
    "race",
    "record",
    "rte",
    "sciq",
    "siqa",
    "squadv2",
    "sst2",
    "swag",
    "toxigen",
    "triviaqa",
    "webqs",
    "wic",
    "wikitext",
    "winogrande",
    "wnli",
    "wsc273",
    "wsc",
    "xnli_eu",
)


@pytest.mark.parametrize("suite_key", SINGLE_SUITE_SPECS, ids=SINGLE_SUITE_SPECS)
def test_llama3_2_transformers_single_suite_spec_full_model_eval(
    capsys: pytest.CaptureFixture[str],
    suite_key: str,
) -> None:
    run_suite_spec(capsys, suite_key)
