"""Evalution package."""

from evalution.config import Model
from evalution.engines import Transformer
from evalution.results import RunResult, SampleResult, TestResult
from evalution.runtime import EngineBuilder, EvaluationRun, engine, run
from evalution.suites import (
    ARCEasy,
    ARCChallenge,
    BaseMultipleChoiceSuite,
    BaseTestSuite,
    BoolQ,
    CB,
    COPA,
    GSM8K,
    GSM8KPlatinum,
    HellaSwag,
    MMLU,
    MultipleChoiceSample,
    OpenBookQA,
    PIQA,
    RTE,
    SST2,
    TestSuite,
    WiC,
    WinoGrande,
    arc_easy,
    arc_challenge,
    boolq,
    cb,
    copa,
    choice_index_from_labels,
    f1_for_label,
    gsm8k,
    gsm8k_platinum,
    hellaswag,
    macro_f1,
    mmlu,
    openbookqa,
    piqa,
    rte,
    question_answer_prompt,
    sst2,
    wic,
    winogrande,
)
from evalution.yaml import python_from_yaml, run_yaml

__all__ = [
    "ARCEasy",
    "ARCChallenge",
    "BaseMultipleChoiceSuite",
    "BaseTestSuite",
    "BoolQ",
    "CB",
    "COPA",
    "EngineBuilder",
    "EvaluationRun",
    "GSM8K",
    "GSM8KPlatinum",
    "HellaSwag",
    "MMLU",
    "Model",
    "MultipleChoiceSample",
    "OpenBookQA",
    "PIQA",
    "RTE",
    "SST2",
    "RunResult",
    "SampleResult",
    "TestSuite",
    "TestResult",
    "Transformer",
    "Transformers",
    "arc_easy",
    "arc_challenge",
    "boolq",
    "cb",
    "copa",
    "choice_index_from_labels",
    "engine",
    "f1_for_label",
    "gsm8k",
    "gsm8k_platinum",
    "hellaswag",
    "macro_f1",
    "mmlu",
    "openbookqa",
    "piqa",
    "rte",
    "python_from_yaml",
    "question_answer_prompt",
    "sst2",
    "run",
    "run_yaml",
    "wic",
    "winogrande",
]

Transformers = Transformer
